--- #YAML:1.0
name:               NexStarCtl
version:            0.07
abstract:           NexStarCtl - API to control NexStar compatible telescopes
author:
    - Rumen Bogdanovski <rumen@skyarchive.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Device::SerialPort:  0.1
requires:
    Device::SerialPort:  0.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
